apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: bankr-secretstore
  namespace: bankr
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /components/bankr-secrets.json
  - name: nestedSeparator
    value: "."
